### PR TITLE
add support for using password for keyfile passed in via dictionary

### PR DESCRIPTION
**Pull request by carl-wallace**
add support for using password for keyfile passed in via sslp dictionary. works with load_cert_chain as described https://docs.python.org/3/library/ssl.html#ssl.SSLContext

### CODE REVIEW

**Comment by methane** [comment]
Would you provide a link of MySQL option?

**Comment by methane** [comment]
I can not find MySQL support this. I don't think we need this although MySQL don't support it.

**Comment by carl-wallace** [comment]
Impatient much? You ask for link, give no time to reply and then close (after letting this sit for months)? This is a mod that I am using, FWIW. Look at the API that is called. Why do you say not supported?

**Comment by methane** [comment]
> Impatient much? You ask for link, give no time to reply and then close (after letting this sit for months)?

Sorry for bothering you.  I want to reformat code and close all pull requests before it.
So I searched the MySQL option by myself, instead of waiting reply. And I can not find any MySQL option.
If you have a link to MySQL option, please provide it?

>  FWIW. Look at the API that is called. Why do you say not supported?

I want to keep this library maintainable.  Rejecting requests not considered so useful is very important to keep the project maintainable.
And if it is so useful, why MySQL doesn't support it?  I usually rejects features MySQL doesn't support.

**Comment by carl-wallace** [comment]
I have run into the problem with MySQL in a C/C++ library as well and made similar mods there (albeit not submitted as yet as a PR). It is useful because keeping plaintext private keys around is not a good practice. To turn your question around, the lower level API invoked by the mod I submitted *does* support it. Why would it support having a password on the P12 object if it were not useful?

**Comment by methane** [comment]
I don't what "mod" means. I don't know how much is it useful. But if it is really useful for many users, it must be supported by MySQL Connector/C and mysql command.  So if you believe it is really useful very much, please request it to MySQL first.  If it is accepted, I will follow MySQL.

Anyway, PyMySQL supports passing SSLContext object.  You can use all ssl APIs already.

**Pull request closed without merging**
