### PR TITLE
Use keyword only argument

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by iamgd67** [comment]
wondering why change `connect` `host` arg oder, while this will break all code not using keyword but postion arguments.

**Comment by methane** [comment]
Oh, that's my fault. I should made all arguments keyword-only.

**Comment by iamgd67** [comment]
don't really understand what you mean by "all arguments keyword-only", I think lattest code still can pass position arguments by `connect('localhost','user','pass')`

**Comment by methane** [comment]
> don't really understand what you mean by "all arguments keyword-only", I think lattest code still can pass position arguments by `connect('localhost','user','pass')`

Yes, and it's my fault. I had to forbid it when changing arguments order.

**Pull request merged**
