### PR TITLE
add test case to test string is not trim

### PR DESCRIPTION
**Pull request by Ting-y**
Test case for #371

### CODE REVIEW

**Comment by methane** [comment]
Your test is passed on Travis.
PyMySQL doesn't trim strings.

**Comment by Ting-y** [comment]
If i want to trim the strings, what is the best way to do it?

**Comment by methane** [comment]
str.strip()

**Comment by Ting-y** [comment]
It there any way that i can override or extend the fetch method? and should i modify in pymysql? Is there any reason why not trim the space in pymysql library?

**Comment by methane** [comment]
I can't catch what you say.

Didn't #371 say "PyMySQL trims strings unexpectedly"?
Did you said "PyMySQL should trim strings (=breaks user data)"?

**Comment by Ting-y** [comment]
Sorry for the confuse question.

I was trying to ask, how to make PyMySQL trim the strings and i want to modify the PyMySQL library instead change my own application.

**Comment by methane** [comment]
Use CHAR instead of VARCHAR

**Comment by Ting-y** [comment]
Its a good alternative, but i am not able to change my existing tables structure tho.

**Comment by grooverdan** [comment]
@Ting-y , its PyMyQL's job to return data exactly how it is in the database. Modifying your own application or the data in the database is the correct solution. Some people expect trailing spaces to be returned so a change in behaviour isn't acceptable for PyMySQL.

If you'd like to clean up your data so no data columns contain leading or trailing spaces:
<pre>
Update tbl set data=TRIM(data)
</pre>

On application changes, If you'd like to return trimmed data you can use the str.strip() python method as mentioned earlier.

If you'd like to return a stripped data in a query:
<pre>
Select TRIM(data) from tbl
</pre>

Hope one of these methods satisfies your needs.

**Comment by methane** [comment]
@Ting-y You can inherit cursor and wrap original fetch* methods.
You can pass your cursor class to connection through `cursorclass` keyword argument.

**Pull request closed without merging**
