### PR TITLE
Remove old_password support

### PR DESCRIPTION
**Pull request by methane**

### CODE REVIEW

**Comment by AmericanY** [comment]
```
Traceback (most recent call last):
  File "/root/american/script.py", line 95, in <module>
    trio.run(main, parser.parse_args())
  File "/usr/local/lib/python3.9/site-packages/trio/_core/_run.py", line 1932, in run
    raise runner.main_task_outcome.error
  File "/root/american/script.py", line 72, in main
    nurse.start_soon(
  File "/usr/local/lib/python3.9/site-packages/trio/_core/_run.py", line 815, in __aexit__
    raise combined_error_from_nursery
  File "/root/american/script.py", line 31, in worker
    async with trio_mysql.connect(host=ip, user=user, password=password, connect_timeout=2) as connection:
  File "/usr/local/lib/python3.9/site-packages/trio_mysql/connections.py", line 616, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.9/site-packages/trio_mysql/connections.py", line 670, in connect
    await self._request_authentication()
  File "/usr/local/lib/python3.9/site-packages/trio_mysql/connections.py", line 974, in _request_authentication
    data = _auth.scramble_old_password(self.password, self.salt) + b"\0"
AttributeError: module 'trio_mysql._auth' has no attribute 'scramble_old_password'
```

@methane @sethmurphy

**Comment by smurfix** [comment]
Thanks, I'll look into it

**Comment by AmericanY** [comment]
@smurfix You welcome. thanks as well :)

**Comment by any0n3** [comment]
Me too having the same issue. please fix it

**Pull request merged**
