### PR TITLE
Add context manager to Connection.

### LINKED ISSUE #735: With + Connection - returns cursor rather than the connection, doesn't close connection on exit
By returning a cursor rather than a connection, extra code needs to be written to handle exceptions and close the connection. Why not return a connection object, then a user can use a second nested with to get a cursor object. This way, wherever an error occurs, the cursors/connections will be neatly closed, and tracebacks will nicely propagate.

I noticed this was a problem when using SSH, and the tunnel wasn't getting decommissioned because the DB connection was still active. Other users also having this problem:

https://stackoverflow.com/questions/31214658/can-i-use-pymysql-connect-with-with-statement

Relevant lines in the code:

https://github.com/PyMySQL/PyMySQL/blob/09040abb0a8153b68b76113539632e7eaa53ce69/pymysql/connections.py#L494

https://github.com/PyMySQL/PyMySQL/blob/09040abb0a8153b68b76113539632e7eaa53ce69/pymysql/connections.py#L498

### PR DESCRIPTION
**Pull request by cmauro1**
Fixes #735.

### CODE REVIEW

**Comment by j08lue** [comment]
Why was the context manager functionality removed in the first place? Would you prefer a different way to use contexts with connection objects?

**Comment by methane** [comment]
See #735.

**Comment by methane** [comment]
I will merge this before releasing 1.0.
But current master branch is for 0.10.

**Comment by j08lue** [comment]
I see, thank you.

**Pull request merged**
