### PR TITLE
Birm 376

### PR DESCRIPTION
**Pull request by birm**
Referencing a feature request in #376. This is one of a handful of ways to handle file objects in addition to file paths for LoadLocalFile with minimal code and functionality change.

### CODE REVIEW

**Comment by methane** [comment]
I don't like the API.
What is your intention?  Do you want to help this project and find the issue?
Or you want the feature?  If so, what's your real needs?

**Comment by birm** [comment]
I am looking to help the project.

**Comment by methane** [comment]
Thanks.  But I don't want to add neither new API or feature without very strong requirement.

If you can help this project, these should be done before adding new features.

* Use pytest instead of unittest2
* Stop setup two connection in `setUp`.
* Use docker to setup MySQL 5.1 and 5.7 on Travis-CI.
* Share more code (tests and cursor) with `mysqlclient-python`

**Comment by birm** [comment]
Okay. I'll put those in as issues and close this PR.

**Pull request closed without merging**
